language: android
sudo: false
android:
  components:
  - build-tools-23.0.1
  - android-23
  - extra-android-support
  - extra-android-m2repository
script:
- ./gradlew :app:assembleRelease
before_install:
- openssl aes-256-cbc -K $encrypted_59c5087c0788_key -iv $encrypted_59c5087c0788_iv
  -in dy.keystore.enc -out keys/dy.keystore -d
